<a href="https://colab.research.google.com/github/Vonewman/Algo/blob/master/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python for Data Science

In [4]:
import numpy as np

## Creating Arrays from Python list

In [6]:
# integer array
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [7]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [8]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [9]:
# nested list results in multidimensional arrays
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

In [10]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.random.random((1, 3))

array([[0.5488135 , 0.71518937, 0.60276338]])

In [18]:
np.random.normal(0, 1, (3, 3))

array([[-2.2683282 ,  1.33354538, -0.84272405],
       [ 1.96992445,  1.26611853, -0.50587654],
       [ 2.54520078,  1.08081191,  0.48431215]])