<a href="https://colab.research.google.com/github/Vonewman/Algo/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is Pytorch?


It's a Python-based scientific computing package tageted at two sets of audiences:

* A replacement for numpy to use the power of GPUs
* A deep learning research platform that provides maximum flexibility and speed


## Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, unitialized:

In [2]:
x = torch.empty(5, 3)
x

tensor([[1.2158e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])

Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.1652, 0.3286, 0.5052],
        [0.4280, 0.6434, 0.6403],
        [0.0768, 0.0502, 0.2210],
        [0.8444, 0.3370, 0.7798],
        [0.6892, 0.4368, 0.6912]])

Construct a matrix filled zeros and of dtype long:

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.7907,  1.8372,  2.2216],
        [-0.9875,  1.3778,  0.7067],
        [-0.4040, -1.1663,  0.7663],
        [ 0.6695,  0.0164,  1.1405],
        [ 0.8131,  0.4457,  0.9370]])


Get its size:

In [7]:
print(x.size())

torch.Size([5, 3])


## Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

Addition: syntax 1

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.8717,  2.3861,  2.6604],
        [-0.3117,  1.9891,  1.5575],
        [ 0.5548, -0.7309,  0.8240],
        [ 1.4535,  0.1283,  1.6851],
        [ 0.8366,  0.6436,  1.6821]])


Addition: syntax 2

In [9]:
print(torch.add(x, y))

tensor([[ 0.8717,  2.3861,  2.6604],
        [-0.3117,  1.9891,  1.5575],
        [ 0.5548, -0.7309,  0.8240],
        [ 1.4535,  0.1283,  1.6851],
        [ 0.8366,  0.6436,  1.6821]])


Addition: providing an output tensor as argument

In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.8717,  2.3861,  2.6604],
        [-0.3117,  1.9891,  1.5575],
        [ 0.5548, -0.7309,  0.8240],
        [ 1.4535,  0.1283,  1.6851],
        [ 0.8366,  0.6436,  1.6821]])


Addition: in-place

In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.8717,  2.3861,  2.6604],
        [-0.3117,  1.9891,  1.5575],
        [ 0.5548, -0.7309,  0.8240],
        [ 1.4535,  0.1283,  1.6851],
        [ 0.8366,  0.6436,  1.6821]])


In [12]:
print(x[:, 1])

tensor([ 1.8372,  1.3778, -1.1663,  0.0164,  0.4457])


Resizing: If you want to resize/reshape tensor, you can use torch.view:

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)   # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use `.item()` to get the value as a Python number

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6947])
-0.6947053670883179


## Numpy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.


## Converting a Torch Tensor to a Numpy Array

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting Numpy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

Tensors can be moved onto any device using the `.to` method.

In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([0.3053], device='cuda:0')
tensor([0.3053], dtype=torch.float64)
