<a href="https://colab.research.google.com/github/Vonewman/Algo/blob/master/What_is_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensors

In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.8734e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0840, 0.6532, 0.3874],
        [0.7766, 0.6703, 0.6414],
        [0.0863, 0.5580, 0.7100],
        [0.4444, 0.9905, 0.5312],
        [0.9485, 0.1269, 0.2572]])


Construct a matrix filled zeros and of dtype long:

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.3120, -0.9032,  2.4810],
        [-0.5026,  0.6925,  0.9022],
        [-0.3848, -0.7636,  1.7760],
        [ 0.0234, -0.0076,  0.1956],
        [ 0.7948,  0.0772,  0.3856]])


In [7]:
print(x.size())

torch.Size([5, 3])


## Operations

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.8653, -0.7982,  2.6446],
        [ 0.4094,  1.2808,  0.9991],
        [ 0.0813,  0.1956,  1.8770],
        [ 0.3581,  0.9329,  0.7267],
        [ 1.0292,  0.7599,  1.2973]])
